version: "3.7"

services:
  database:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    ports: 
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=adonis_db
